#77
Dash-Inside/store_client pull request #78
Opened 2023-08-16 15:22 UTC by XxJ0TaR0Xx

2023-08-16 15:49 UTC, danwirele approved these changes

2023-08-16 15:49 UTC, danwirele commented on lib/src/data/models/message_model.dart
> +  factory MessageModel.fromMap(Map<String, dynamic> map) {
доработка

2023-08-16 15:50 UTC, danwirele requested changes
исправь

2023-08-17 00:26 UTC, pocket-red-fox commented on lib/src/data/models/message_model.dart
> +  factory MessageModel.fromMap(Map<String, dynamic> map) {
Желательно выставлять комментарии непосредственно после строк с ошибками, как ты можешь увидеть - последние 4 строки здесь не дают с ходу понять, что изменять. На будущее так же прошу писать нормально то, что необходимо поправить людям. Иначе, мне лично, проверить вас становится крайне тяжелой задачей.

2023-08-17 00:27 UTC, danwirele commented on lib/src/data/models/message_model.dart
> +  factory MessageModel.fromMap(Map<String, dynamic> map) {
Я дал устное объяснение

2023-08-17 15:20 UTC, danwirele approved these changes

2023-08-17 15:20 UTC, merged